export const VueUiSparkStackbarConfig = {
  style: {
    backgroundColor: "#fff",
    fontFamily: "inherit",
    animation: { show: true, animationFrames: 60 },
    bar: { gradient: { show: true, intensity: 40, underlayerColor: "#FFFFFF" } },
    legend: {
      margin: "6px 0 0 0",
      textAlign: "left",
      show: true,
      fontSize: 12,
      name: { color: "#2D353C", bold: false },
      value: { show: true, bold: false, color: "#2D353C", prefix: "", suffix: "", rounding: 0 },
      percentage: { show: true, bold: true, color: "#2D353C", rounding: 1 },
    },
  },
};

export const VueUiDonutConfig = {
  responsive: true,
  useBlurOnHover: true,
  useCssAnimation: true,
  style: {
    fontFamily: "inherit",
    chart: {
      useGradient: true,
      gradientIntensity: 40,
      backgroundColor: "#FFFFFF",
      color: "#1A1A1A",
      layout: {
        labels: {
          dataLabels: { show: true, useLabelSlots: false, hideUnderValue: 3, prefix: "", suffix: "" },
          value: { rounding: 0, show: true },
          percentage: { color: "#1A1A1A", bold: true, fontSize: 18 },
          name: { color: "#1A1A1A", bold: false, fontSize: 14 },
          hollow: {
            show: true,
            total: {
              show: true,
              bold: false,
              fontSize: 18,
              color: "#1A1A1A",
              text: "Hedef",
              offsetY: -6,
              value: { color: "#1A1A1A", fontSize: 16, bold: true, suffix: "", prefix: "€", offsetY: -2, rounding: 0 },
            },
            average: {
              show: false,
              bold: false,
              fontSize: 18,
              color: "#1A1A1A",
              text: "Average",
              offsetY: 0,
              value: { color: "#1A1A1A", fontSize: 18, bold: true, suffix: "", prefix: "", offsetY: 6, rounding: 0 },
            },
          },
        },
        donut: { strokeWidth: 55, borderWidth: 2, useShadow: false, shadowColor: "#1A1A1A" },
      },
      comments: { show: false, showInTooltip: true, width: 100, offsetX: 0, offsetY: 0 },
      legend: { backgroundColor: "#F3F4F6", color: "#1A1A1A", show: false, fontSize: 16, bold: false, roundingValue: 0, roundingPercentage: 0 },
      tooltip: {
        show: true,
        color: "#1A1A1A",
        backgroundColor: "#F3F4F6",
        fontSize: 14,
        showValue: true,
        showPercentage: true,
        roundingValue: 0,
        roundingPercentage: 0,
        customFormat: null,
        borderRadius: 4,
        borderColor: "#e1e5e8",
        borderWidth: 1,
        backgroundOpacity: 90,
        position: "center",
        offsetY: 24,
      },
    },
  },
  userOptions: {
    show: false,
    buttons: { tooltip: true, pdf: true, img: true, csv: true, table: true, labels: true, fullscreen: true },
    buttonTitles: {
      open: "Open options",
      close: "Close options",
      tooltip: "Toggle tooltip",
      pdf: "Download PDF",
      csv: "Download CSV",
      img: "Download PNG",
      table: "Toggle table",
      labels: "Toggle labels",
      fullscreen: "Toggle fullscreen",
    },
  },
  table: {
    show: false,
    responsiveBreakpoint: 300,
    columnNames: { series: "Series", value: "Value", percentage: "Percentage" },
    th: { backgroundColor: "#F3F4F6", color: "#1A1A1A", outline: "none" },
    td: { backgroundColor: "#F3F4F6", color: "#1A1A1A", outline: "none", roundingValue: 0, roundingPercentage: 0 },
  },
};
